# application.yml - Consolidated configuration

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logisticsdb
    username: logistics
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: logistics

  flyway:
    schemas: logistics
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false

  data:
    redis:
      host: your-redis-host
      port: 6379

management:
  health:
    redis:
      enabled: false

server:
  port: 8080
  servlet:
    context-path: /api