# Development environment configuration
spring:
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/identityaccess
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # SQL initialization
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true

  # Flyway configuration (disabled)
  flyway:
    enabled: false

# Server configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# JWT configuration
jwt:
  secret: ${JWT_SECRET:dev_secret_key_at_least_64_chars_long_for_hmac_sha_256_encryption}
  expiration: 86400000  # 1 day in milliseconds

# Encryption configuration
encryption:
  key: ${ENCRYPTION_KEY:}

# gRPC configuration
grpc:
  server:
    port: 9090

# Logging
logging:
  level:
    root: INFO
    com.wizdevtech: DEBUG
    org.hibernate.SQL: DEBUG