# Production environment configuration
spring:
  # Database configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:identityaccess}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000

  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # SQL initialization (disabled for production)
  sql:
    init:
      mode: never

  # Flyway configuration (disabled)
  flyway:
    enabled: false

# Server configuration
server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: never
    include-binding-errors: never
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/plain
    min-response-size: 2048

# JWT configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}  # 1 day in milliseconds

# Encryption configuration
encryption:
  key: ${ENCRYPTION_KEY}

# gRPC configuration
grpc:
  server:
    port: ${GRPC_PORT:9090}

# Logging
logging:
  level:
    root: INFO
    com.wizdevtech: INFO
    org.hibernate: WARN
    org.springframework: WARN
  file:
    name: /var/log/identityaccess/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7