# Application configuration file (YAML format)
# Contains database connection, server settings, etc.

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: product-service

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: productuser
    password: productpass
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Flyway migration configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /api

# Logging configuration
logging:
  level:
    com.productcatalog: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework: INFO

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method