version: '3.8'

services:
  postgres-test:
    image: postgres:15
    container_name: logistics-test-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logistics_test
      POSTGRES_USER: postgres
    ports:
      - "5433:5432" # Map host port 5433 to container 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - test-pg-data:/var/lib/postgresql/data

volumes:
  test-pg-data: